// Pure client-side HTML sanitizer using native browser DOMParser.
// Prevents stored XSS attacks when rendering Markdown-rendered HTML.
export function sanitizeHtml(html: string): string {
  if (!html) return '';

  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  // Whitelist of allowed HTML elements generated by marked markdown parser
  const whitelistTags = new Set([
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'br', 'hr',
    'ul', 'ol', 'li', 'pre', 'code', 'blockquote',
    'strong', 'em', 'del', 'a', 'span', 'div',
    'table', 'thead', 'tbody', 'tr', 'th', 'td'
  ]);

  // Whitelist of allowed attributes per element
  const whitelistAttributes: Record<string, Set<string>> = {
    'a': new Set(['href', 'target', 'rel', 'title']),
    'code': new Set(['class']),
    'pre': new Set(['class']),
    'span': new Set(['class']),
    'div': new Set(['class'])
  };

  function cleanNode(node: Node): Node | null {
    if (node.nodeType === Node.TEXT_NODE) {
      return node.cloneNode(true);
    }

    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as Element;
      const tagName = el.tagName.toLowerCase();

      // If element is not in whitelist, strip tag but keep safe children content
      if (!whitelistTags.has(tagName)) {
        const fragment = doc.createDocumentFragment();
        for (const child of Array.from(el.childNodes)) {
          const cleaned = cleanNode(child);
          if (cleaned) fragment.appendChild(cleaned);
        }
        return fragment;
      }

      const newEl = doc.createElement(tagName);

      // Copy only whitelisted attributes
      const allowedAttrs = whitelistAttributes[tagName] || new Set();
      for (const attr of Array.from(el.attributes)) {
        const attrName = attr.name.toLowerCase();
        if (allowedAttrs.has(attrName)) {
          let val = attr.value;
          
          // Defend against javascript: URIs in anchor hrefs
          if (tagName === 'a' && attrName === 'href') {
            const trimmed = val.trim().toLowerCase();
            if (trimmed.startsWith('javascript:') || trimmed.startsWith('data:') || trimmed.startsWith('vbscript:')) {
              val = '#';
            }
          }
          newEl.setAttribute(attrName, val);
        }
      }

      // Recursively clean children
      for (const child of Array.from(el.childNodes)) {
        const cleaned = cleanNode(child);
        if (cleaned) newEl.appendChild(cleaned);
      }

      return newEl;
    }

    return null;
  }

  const body = doc.body;
  const cleanFragment = doc.createDocumentFragment();
  for (const child of Array.from(body.childNodes)) {
    const cleaned = cleanNode(child);
    if (cleaned) cleanFragment.appendChild(cleaned);
  }

  const container = doc.createElement('div');
  container.appendChild(cleanFragment);
  return container.innerHTML;
}
